name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install sshpass
        run: sudo apt install -y sshpass

      - name: Build
        run: sshpass -p '${{ secrets.PASSWORD }}' ssh -o StrictHostKeyChecking=no -o ProxyCommand="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -W '[%h]:%p' jump@dfw.proxy.infra.aarch64.com" ${{ secrets.ORIGIN }} -p 22777 "sudo -u fosshost sh -c 'cd /home/fosshost/fosshost.org && git fetch --all && git reset --hard origin/main && npm i && npm run build'"

      - name: Restart
        run: sshpass -p '${{ secrets.PASSWORD }}' ssh -o StrictHostKeyChecking=no -o ProxyCommand="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -W '[%h]:%p' jump@dfw.proxy.infra.aarch64.com" ${{ secrets.ORIGIN }} -p 22777 "systemctl restart fosshostorg"
